// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mhyrgoittmlcoyxdcotm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1oeXJnb2l0dG1sY295eGRjb3RtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzNjgyMDcsImV4cCI6MjA2OTk0NDIwN30.ctE94_jXYOcbVL6ZKhdpA-xauE_S7Zj-c1gPtgtcCy4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});